### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by EladBezalel** [nachos/file-explorer#1]
Enable basic usage of file explorer with navigation

**Comment by EladBezalel** [comment]
@omrilitov @doodledood I'm almost done but there's a problem,
When navigating to a folder with hidden/protected files everything becomes chaos,
In [this](http://stackoverflow.com/a/8927970/890293) thread he says that we should use native to get this information but in the comments there's [this](https://github.com/stevenvachon/hidefile)
we should consider both options

**Comment by omrilitov** [comment]
@EladBezalel @doodledood
https://github.com/stevenvachon/winattr
It uses fswin which is native
Is it good enough?

**Comment by EladBezalel** [comment]
Whatever works best.. I'll check it today

**Comment by doodledood** [comment]
I would advice not using it directly but using a wrapper around it, as I am taking into consideration the cross platform nature of the project. That way, when we decide to support another os, you do not need to change anything.

**Comment by omrilitov** [comment]
So maybe we should just look at fswin's source,  and add it to our native

**Comment by doodledood** [comment]
Yes, will take a look at it. As I already noticed, it supports only Windows. We can use it as a part of a native api.

**Comment by doodledood** [comment]
#https://github.com/nachos/native-api/issues/4
